apiVersion: v1
kind: Service
metadata:
 labels:
  app.kubernetes.io/instance: graphite
  app.kubernetes.io/name: graphite
 name: graphite-lb
spec:
 type: LoadBalancer
 ports:
 - port: 8080
   targetPort: 8080
 selector:
  app.kubernetes.io/instance: graphite
  app.kubernetes.io/name: graphite
