apiVersion: v1
kind: Service
metadata:
  name: graphite-backend 
  labels:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    helm.sh/chart: {{ include "graphite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: NodePort
  ports:
    - name: graphite-pickle
      port: 2004
      protocol: TCP
    - name: graphite-plain
      port: 2003
      protocol: TCP
    - name: graphite-gui
      port: {{ .Values.service.port }}
      protocol: TCP
    - name: aggregate-plain
      port: 2023
      protocol: TCP
    - name: aggregate-pickl
      port: 2024
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
