apiVersion: v1
kind: Service
metadata:
  name: statsd
  labels:
    app: statsd
spec:
  type: NodePort
  selector:
    app: graphite
  clusterIP: None
  ports:
  - port: 8125
    name: statsd
    protocol: UDP
  - port: 8126
    name: statsd-admin
    protocol: TCP
