apiVersion: v1
kind: Service
metadata:
  name: {{ template "graphite.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    helm.sh/chart: {{ include "graphite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: statsd
      port: 8125
      protocol: {{ .Values.statsd.interface }}
  selector:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
