apiVersion: v1
kind: Service
metadata:
 labels:
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/name: {{ include "graphite.name" . }}
 name: graphite-lb
 spec:
 type: LoadBalancer
 ports:
 - port: 8080
   targetPort: 8080
 selector:
  app.kubernetes.io/name: {{ include "graphite.name" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
